-- set minimum xmake version
set_xmakever("2.8.2")

-- includes
includes("lib/commonlibsse-ng")

-- include generated dependencies if they exist
if os.exists("xmake-deps.lua") then
    includes("xmake-deps.lua")
end

-- set project
set_project("Intellightent")
set_version("1.0.0")
set_license("GPL-3.0")

-- set defaults
set_languages("c++23")
set_warnings("allextra")

-- set policies
set_policy("package.requires_lock", true)

-- add rules
add_rules("mode.debug", "mode.releasedbg")
add_rules("plugin.vsxmake.autoupdate")

-- targets
target("Intellightent")
-- add dependencies to target
add_deps("commonlibsse-ng")

on_load(function(target)
    import("core.base.json")
    local vcpkg = json.loadfile("vcpkg.json")

    -- Set project metadata
    target:set("version", vcpkg.version)
    target:set("license", vcpkg.license)

    -- Add packages dynamically
    if vcpkg.dependencies then
        for _, dep in ipairs(vcpkg.dependencies) do
            local dep_name = dep
            if type(dep) == "table" and dep.name then
                dep_name = dep.name
            end
            target:add("packages", "vcpkg::" .. dep_name)
        end
    end

    -- Capitalize the first letter for the DLL name (Intellightent)
    -- vcpkg names are lowercase
    local name = vcpkg.name:gsub("^%l", string.upper)
    target:set("basename", name)

    target:set("configvar", "VERSION_MAJOR", vcpkg.version:split("%.")[1])
    target:set("configvar", "VERSION_MINOR", vcpkg.version:split("%.")[2])
    target:set("configvar", "VERSION_PATCH", vcpkg.version:split("%.")[3])
    target:set("configvar", "VERSION_STRING", vcpkg.version)
end)

-- add commonlibsse-ng plugin
add_rules("commonlibsse-ng.plugin", {
    name = "Intellightent",
    author = "libxse",
    description = "Intellightent Skyrim Mod",
})

-- add src files
add_files("src/**.cpp")
add_headerfiles("src/**.h")
add_includedirs("src")
set_pcxxheader("src/pch.h")
add_configfiles("src/Version.h.in")

-- task to update dependencies from vcpkg.json
task("update_deps")
set_menu({
    usage = "xmake update_deps",
    description = "Update dependencies from vcpkg.json",
})
on_run(function()
    import("core.base.json")
    local vcpkg = json.loadfile("vcpkg.json")

    local file = io.open("xmake-deps.lua", "w")
    if file then
        file:write("-- This file is generated by xmake update_deps. Do not edit manually.\n\n")

        if vcpkg.dependencies then
            for _, dep in ipairs(vcpkg.dependencies) do
                local dep_name = dep
                if type(dep) == "table" and dep.name then
                    dep_name = dep.name
                end
                file:write(string.format('add_requires("vcpkg::%s")\n', dep_name))
            end
        end

        file:close()
        print("Generated xmake-deps.lua")
    end
end)
